"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/context/AuthContext";
import { BodyRegion, Symptom, RefiningQuestion } from "@/lib/types/analyzer";
import {
  ArrowLeft,
  Loader2,
  Stethoscope,
  CheckCircle2,
  Circle,
  ArrowRight,
  Brain,
  Lightbulb,
  HelpCircle,
  MessageSquare,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";

// Sample questions - In production, these would be generated by AI based on symptoms
const generateQuestions = (symptoms: Symptom[], regionName: string): RefiningQuestion[] => {
  const baseQuestions: RefiningQuestion[] = [
    {
      id: "q1",
      question: "How long have you been experiencing these symptoms?",
      explanation: "Duration helps differentiate acute conditions from chronic ones and guides urgency of evaluation.",
      options: [
        { id: "q1_a", text: "Less than 24 hours", clinical_significance: "Acute onset - may indicate infection, injury, or vascular event" },
        { id: "q1_b", text: "1-7 days", clinical_significance: "Subacute - common for infections and inflammatory conditions" },
        { id: "q1_c", text: "1-4 weeks", clinical_significance: "Prolonged - may need workup for underlying cause" },
        { id: "q1_d", text: "More than 1 month", clinical_significance: "Chronic - suggests ongoing condition requiring evaluation" },
      ],
    },
    {
      id: "q2",
      question: "How would you rate the severity of the primary symptom?",
      explanation: "Severity assessment helps prioritize differential diagnoses and determine need for urgent intervention.",
      options: [
        { id: "q2_a", text: "Mild - noticeable but not limiting activities", clinical_significance: "May be appropriate for conservative management" },
        { id: "q2_b", text: "Moderate - affecting daily activities", clinical_significance: "Warrants evaluation and possible treatment" },
        { id: "q2_c", text: "Severe - significantly limiting function", clinical_significance: "Requires prompt evaluation" },
        { id: "q2_d", text: "Very severe - unable to perform normal activities", clinical_significance: "May need urgent/emergent care" },
      ],
    },
    {
      id: "q3",
      question: "Is the symptom constant or does it come and go?",
      explanation: "Pattern of symptoms can indicate different underlying pathophysiology.",
      options: [
        { id: "q3_a", text: "Constant - always present", clinical_significance: "Suggests structural or continuous inflammatory process" },
        { id: "q3_b", text: "Intermittent - comes and goes throughout the day", clinical_significance: "May indicate functional or positional component" },
        { id: "q3_c", text: "Episodes - distinct attacks with normal periods", clinical_significance: "Classic for migraines, seizures, or paroxysmal conditions" },
        { id: "q3_d", text: "Progressive - getting worse over time", clinical_significance: "Concerning for expanding lesion or progressive disease" },
      ],
    },
    {
      id: "q4",
      question: "Are there any factors that make the symptoms better or worse?",
      explanation: "Aggravating and alleviating factors provide important diagnostic clues.",
      options: [
        { id: "q4_a", text: "Movement/activity makes it worse", clinical_significance: "Suggests musculoskeletal or structural cause" },
        { id: "q4_b", text: "Rest/lying down makes it better", clinical_significance: "May indicate orthostatic or positional component" },
        { id: "q4_c", text: "Eating affects symptoms", clinical_significance: "Points to GI involvement" },
        { id: "q4_d", text: "No clear pattern identified", clinical_significance: "May need further investigation" },
      ],
    },
    {
      id: "q5",
      question: "Have you experienced any associated symptoms?",
      explanation: "Associated symptoms help narrow the differential and identify systemic involvement.",
      options: [
        { id: "q5_a", text: "Fever or chills", clinical_significance: "Suggests infectious or inflammatory process" },
        { id: "q5_b", text: "Nausea or vomiting", clinical_significance: "May indicate GI involvement or increased intracranial pressure" },
        { id: "q5_c", text: "Weight changes", clinical_significance: "Can suggest metabolic, endocrine, or malignant process" },
        { id: "q5_d", text: "None of the above", clinical_significance: "Isolated symptom - may be localized process" },
      ],
    },
  ];
  
  return baseQuestions;
};

export default function QuestionsPage() {
  const params = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const { user } = useAuth();
  
  const sessionId = params.id as string;
  const regionId = searchParams.get("region");
  const symptomsParam = searchParams.get("symptoms");
  
  const [region, setRegion] = useState<BodyRegion | null>(null);
  const [symptoms, setSymptoms] = useState<Symptom[]>([]);
  const [questions, setQuestions] = useState<RefiningQuestion[]>([]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [showExplanation, setShowExplanation] = useState(false);

  // Parse symptoms and fetch region
  useEffect(() => {
    async function fetchData() {
      setLoading(true);
      
      try {
        // Parse symptoms from URL
        if (symptomsParam) {
          const parsedSymptoms = JSON.parse(decodeURIComponent(symptomsParam));
          setSymptoms(parsedSymptoms);
        }
        
        // Fetch region
        if (regionId) {
          const { data: regionData } = await supabase
            .from("body_regions")
            .select("*")
            .eq("id", regionId)
            .single();
          
          if (regionData) {
            setRegion(regionData);
            
            // Generate questions based on symptoms and region
            const generatedQuestions = generateQuestions(
              symptoms,
              regionData.name
            );
            setQuestions(generatedQuestions);
          }
        }
      } catch (error) {
        console.error("Error:", error);
      } finally {
        setLoading(false);
      }
    }
    
    fetchData();
  }, [regionId, symptomsParam]);

  // Handle option selection
  const handleOptionSelect = (optionId: string) => {
    setSelectedOption(optionId);
  };

  // Handle next question
  const handleNext = () => {
    if (!selectedOption) return;
    
    const currentQuestion = questions[currentQuestionIndex];
    
    // Save answer
    setAnswers(prev => ({
      ...prev,
      [currentQuestion.id]: selectedOption,
    }));
    
    // Move to next question or finish
    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
      setSelectedOption(null);
      setShowExplanation(false);
    } else {
      // All questions answered - navigate to diagnosis
      const answersParam = encodeURIComponent(JSON.stringify({
        ...answers,
        [currentQuestion.id]: selectedOption,
      }));
      
      router.push(
        `/student/analyzer/session/${sessionId}/diagnosis?region=${regionId}&symptoms=${symptomsParam}&answers=${answersParam}`
      );
    }
  };

  // Handle previous question
  const handlePrevious = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(prev => prev - 1);
      const prevQuestion = questions[currentQuestionIndex - 1];
      setSelectedOption(answers[prevQuestion.id] || null);
    }
  };

  if (loading || questions.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin text-emerald-600 mx-auto" />
          <p className="mt-2 text-gray-600">Generating clinical questions...</p>
        </div>
      </div>
    );
  }

  const currentQuestion = questions[currentQuestionIndex];
  const progress = ((currentQuestionIndex + 1) / questions.length) * 100;

  return (
    <div className="max-w-3xl mx-auto">
      {/* Header */}
      <div className="mb-6">
        <Button
          variant="ghost"
          onClick={() => router.back()}
          className="mb-4 text-gray-600 hover:text-gray-900"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back
        </Button>
        
        <div className="bg-gradient-to-r from-emerald-500 to-cyan-500 rounded-2xl p-6 text-white">
          <div className="flex items-center gap-3 mb-2">
            <Brain className="h-8 w-8" />
            <h1 className="text-2xl font-bold">Clinical Questions</h1>
          </div>
          <p className="text-emerald-100">
            Answer these questions to help narrow down the diagnosis
          </p>
        </div>
      </div>

      {/* Progress */}
      <Card className="mb-6">
        <CardContent className="py-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm text-gray-600">
              Question {currentQuestionIndex + 1} of {questions.length}
            </span>
            <span className="text-sm font-medium text-emerald-600">
              {Math.round(progress)}% complete
            </span>
          </div>
          <Progress value={progress} className="h-2" />
        </CardContent>
      </Card>

      {/* Selected Symptoms Summary */}
      <Card className="mb-6 bg-gray-50">
        <CardContent className="py-3">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-sm text-gray-500">Symptoms:</span>
            {symptoms.map((symptom) => (
              <Badge key={symptom.id} variant="secondary" className="text-xs">
                {symptom.name}
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Question Card */}
      <Card className="mb-6">
        <CardHeader>
          <div className="flex items-start gap-3">
            <div className="p-2 bg-emerald-100 rounded-lg">
              <MessageSquare className="h-5 w-5 text-emerald-600" />
            </div>
            <div className="flex-1">
              <CardTitle className="text-lg leading-relaxed">
                {currentQuestion.question}
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                className="mt-2 text-blue-600 hover:text-blue-700 p-0 h-auto"
                onClick={() => setShowExplanation(!showExplanation)}
              >
                <HelpCircle className="h-4 w-4 mr-1" />
                {showExplanation ? "Hide" : "Why this question?"}
              </Button>
            </div>
          </div>
        </CardHeader>
        
        {showExplanation && (
          <div className="mx-6 mb-4 p-4 bg-blue-50 rounded-lg border border-blue-200">
            <div className="flex gap-2">
              <Lightbulb className="h-5 w-5 text-blue-600 flex-shrink-0" />
              <p className="text-sm text-blue-800">{currentQuestion.explanation}</p>
            </div>
          </div>
        )}
        
        <CardContent>
          <div className="space-y-3">
            {currentQuestion.options.map((option) => {
              const isSelected = selectedOption === option.id;
              
              return (
                <div
                  key={option.id}
                  onClick={() => handleOptionSelect(option.id)}
                  className={`p-4 rounded-xl border-2 cursor-pointer transition-all ${
                    isSelected
                      ? "border-emerald-400 bg-emerald-50"
                      : "border-gray-200 hover:border-gray-300 bg-white"
                  }`}
                >
                  <div className="flex items-start gap-3">
                    {isSelected ? (
                      <CheckCircle2 className="h-5 w-5 text-emerald-600 flex-shrink-0 mt-0.5" />
                    ) : (
                      <Circle className="h-5 w-5 text-gray-300 flex-shrink-0 mt-0.5" />
                    )}
                    <div className="flex-1">
                      <p className={`font-medium ${isSelected ? "text-emerald-900" : "text-gray-900"}`}>
                        {option.text}
                      </p>
                      {isSelected && option.clinical_significance && (
                        <p className="text-sm text-emerald-700 mt-2 bg-emerald-100/50 p-2 rounded">
                          <span className="font-medium">Clinical significance: </span>
                          {option.clinical_significance}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Navigation Buttons */}
      <div className="flex items-center justify-between">
        <Button
          variant="outline"
          onClick={handlePrevious}
          disabled={currentQuestionIndex === 0}
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          Previous
        </Button>
        
        <Button
          onClick={handleNext}
          disabled={!selectedOption}
          className="bg-gradient-to-r from-emerald-500 to-cyan-500 hover:from-emerald-600 hover:to-cyan-600"
        >
          {currentQuestionIndex === questions.length - 1 ? (
            <>
              View Diagnosis
              <Stethoscope className="h-4 w-4 ml-2" />
            </>
          ) : (
            <>
              Next Question
              <ArrowRight className="h-4 w-4 ml-2" />
            </>
          )}
        </Button>
      </div>
    </div>
  );
}